### PR TITLE
If client provided forked page use it.

### PR DESCRIPTION
**Pull request by nrn**

### CODE REVIEW

**Comment by nrn** [comment]
This is a partial fix for "Login Required' pages being created by implicit forks from login to read pages. There is another path that would cause this for `action.type === `fork'` also, but i haven't tracked down where it would be triggered.

**Comment by paul90** [comment]
Let's connect this with the related wiki-client PR - https://github.com/fedwiki/wiki-client/pull/308

**Comment by paul90** [comment]
There are two types of fork events, explicit *user deliberately clicks on the fork button*, and implicit *when the user performs some action that would modify the stored page*.

Currently the explicit fork sends the content of the page, [wiki-client pageHandler.coffee#L128-L129](https://github.com/fedwiki/wiki-client/blob/7fc7e69d56f77edb87969f622bfe94bf2c626d23/lib/pageHandler.coffee#L128-L129). It would seem to make sense to use the same mechanism for the implicit fork. Might want to use a different name than `bundle.item`. Ward is concerned with overloading `item`, so using a different common name in both types of fork event would help with clarity. `forkPage` looks like a good name.

**Comment by paul90** [comment]
Oh, and like the explicit/deliberate fork event the page should not be included in the fork event in the journal.

**Comment by paul90** [comment]
Deleting `action.forkPage` before action gets added to the journal, and changing the explicit fork to use `forkPage` rather than `item`.

As far as I can see, as long as the correct client/server pair are used, `remoteGet()` should never get called, as both types of fork should be sending the page.

**Comment by WardCunningham** [comment]
Thank you for this. Merge at will.

**Comment by paul90** [comment]
As discussed on call, adding the date to the implicit fork event.

**Comment by paul90** [comment]
Published as + wiki-server@0.23.0

**Pull request merged**
