### PR TITLE
Recycle pages being removed

### PR DESCRIPTION
**Pull request by paul90**
Work in progress, see related client update fedwiki/wiki-client#197.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I wonder if there are any risks associated with merging this in advance of through testing of the corresponding client side? We would want to be sure that deletes come from logged in users.

**Comment by paul90** [comment]
I think it is probably best holding off until we are ready to merge the client as well. There are also a few more changes that are need here as well.

**Comment by WardCunningham** [comment]
Looks promising. Could handle DELETE too, for that most final of deletes.

Safe Delete:
- retrieve create version
- fork it (interpreted as DELETE)

Recycler Delete:
- retrieve original from recycler
- retrieve create version
- fork it (interpreted as recycler DELETE)

Two steps to hid from public, five to make page vanish.

**Comment by paul90** [comment]
Delete from recycler is not committed yet - holding off while I finalize the recycler plug-in that brings this together.

**Comment by paul90** [comment]
> Recycler Delete:
> 
> -     retrieve original from recycler
> -     retrieve create version
> -     fork it (interpreted as recycler DELETE)
> 

Currently I am using a recycler plug-in, that lists the pages in the recycler, each has a delete button and there is an 'empty recycler' button. So, only two steps to delete from recycler.

- open page with recycler plugin
- press the delete button that's beside the page

Retrieving page from recycler is three steps

- open page with recycler plugin
- open page from the recycler
- fork it - this will swap the page in the recycler with the copy in the site, if there is one

**Comment by WardCunningham** [comment]
I'm liking the way this is going and look forward to a demo.

**Pull request merged**
