### PR TITLE
Set argv.url even if port is 80

### PR DESCRIPTION
**Pull request by alltom**
The previous version set argv.url to undefined, which causes the server to crash when it attempts to launch. This version sets argv.url to "http://localhost" when port is 80.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I'm guessing that your code is what was intended by the original carelessly scoped 'unless' clause.

I am wondering where the server launch was failing? What made this show up now, four years later?

**Comment by alltom** [comment]
The line that crashes on startup was added in December, 2020: [wikiName = new URL(argv.url).hostname](https://github.com/fedwiki/wiki-server/blob/7f9570d70ebe9288481f769e9865010df106d337/lib/page.coffee#L32), though I see that same pattern has been used [in sitemap.coffee](https://github.com/fedwiki/wiki-server/blob/23af88525d113a9af1414803fec285fb8c72f720/lib/sitemap.coffee#L28) and [in search.coffee](https://github.com/fedwiki/wiki-server/blob/23af88525d113a9af1414803fec285fb8c72f720/lib/search.coffee#L21) for 2 years.

Maybe it's unusual to use port 80 directly now that SSL is standard? Or maybe people don't update their software?

Docker containers on App Engine use the hosts' network stack and I hadn't gotten around to setting up SSL yet, which is why I discovered this bug while setting up [federated-wiki/wiki-docker](https://github.com/federated-wiki/wiki-docker).

**Comment by WardCunningham** [comment]
Thank you for this explanation.

**Comment by WardCunningham** [comment]
published as wiki-server@0.19.4

**Pull request merged**
